import fs from 'node:fs/promises';
const indexPath='public/index.html',commercePath='public/commerce-config.js';
let html=await fs.readFile(indexPath,'utf8');
html=html.replaceAll('DOĞAL MALZEME','PREMİUM KORDON').replaceAll('Doğal ve sürdürülebilir iplikler kullanılır.','Yüksek kaliteli, şekil tutan premium kordon iplikler kullanılır.').replaceAll('NATURAL MATERIALS','PREMIUM CORD').replaceAll('Natural and more sustainable yarns are used.','Made with high-quality, shape-retaining premium cord yarns.');
html=html.replaceAll('assets/products/vita-20260821.jpg','assets/products/vita-20260821.webp').replaceAll('assets/products/vita.webp','assets/products/vita-20260821.webp').replaceAll('assets/products/vita.jpg','assets/products/vita-20260821.webp');
html=html.replaceAll("window.location.href='mailto:hello@trenza.com.tr?subject='+subject+'&body='+body","showToast('Talep gönderilemedi. Lütfen tekrar deneyin.');");
html=html.replaceAll('E-posta uygulaman açılacak','Kaydın doğrudan TRƎNZA\'ya iletilecek');
await fs.writeFile(indexPath,html,'utf8');
let commerce=await fs.readFile(commercePath,'utf8');
commerce=commerce.replace("preRegisterEndpoint:'/api/pre-register',preorderEndpoint:'/api/preorder',checkoutEndpoint:'/api/preorder'","preRegisterEndpoint:'/api/lead',preorderEndpoint:'/api/lead',checkoutEndpoint:'/api/lead'");
await fs.writeFile(commercePath,commerce,'utf8');
console.log('TRƎNZA Worker integration prepared.');